# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/SOC_basic/buoi2/ip_repo/edit_H_Acceleration_IP_v1_0.srcs/sources_1/ip/ila_debug/ila_debug.xci
# IP: The module: 'ila_debug' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SOC_basic/buoi2/ip_repo/edit_H_Acceleration_IP_v1_0.gen/sources_1/ip/ila_debug/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_debug'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/SOC_basic/buoi2/ip_repo/edit_H_Acceleration_IP_v1_0.gen/sources_1/ip/ila_debug/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_debug'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/SOC_basic/buoi2/ip_repo/edit_H_Acceleration_IP_v1_0.gen/sources_1/ip/ila_debug/ila_debug_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_debug'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/SOC_basic/buoi2/ip_repo/edit_H_Acceleration_IP_v1_0.srcs/sources_1/ip/ila_debug/ila_debug.xci
# IP: The module: 'ila_debug' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SOC_basic/buoi2/ip_repo/edit_H_Acceleration_IP_v1_0.gen/sources_1/ip/ila_debug/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_debug'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/SOC_basic/buoi2/ip_repo/edit_H_Acceleration_IP_v1_0.gen/sources_1/ip/ila_debug/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_debug'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/SOC_basic/buoi2/ip_repo/edit_H_Acceleration_IP_v1_0.gen/sources_1/ip/ila_debug/ila_debug_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_debug'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
