`timescale 1ns/1ps

module TB_Median_Filter_Core;

    parameter MEM_ADDR_BITS = 12;
    parameter BUS_ADDR_BITS = MEM_ADDR_BITS + 1;
    parameter DIM_BITS      = 16;
    parameter CLK_PERIOD    = 10;
    parameter BANK_DEPTH    = (1 << MEM_ADDR_BITS);

    parameter MAX_TIMEOUT_POLLS     = 1000000;
    parameter MAX_REPORTED_FAILURES = 32;

    // Same data set generated by median_filter_c_model.zip.
// S? d?ng g?ch chéo xuôi (/) thay cho g?ch chéo ngý?c (\)
    parameter IMAGE_INFO_FILE = "C:/SOC_basic/day6_7_8/Modeling/data/image_info.txt";
    parameter INPUT_HEX_FILE  = "C:/SOC_basic/day6_7_8/Modeling/data/noisy_pixels.hex";
    parameter GOLDEN_HEX_FILE = "C:/SOC_basic/day6_7_8/Modeling/data/denoised_pixels.hex";
    parameter RTL_OUTPUT_FILE = "C:/SOC_basic/day6_7_8/Modeling/data/rtl_tiling_denoised_pixels.hex";

    // Control-space addresses: MSB=1.
    localparam [BUS_ADDR_BITS-1:0] WIDTH_REG_ADDR      = {1'b1, 12'h000};
    localparam [BUS_ADDR_BITS-1:0] HEIGHT_REG_ADDR     = {1'b1, 12'h001};
    localparam [BUS_ADDR_BITS-1:0] LOAD_REG_ADDR       = {1'b1, 12'h002};
    localparam [BUS_ADDR_BITS-1:0] START_REG_ADDR      = {1'b1, 12'h003};
    localparam [BUS_ADDR_BITS-1:0] STOP_REG_ADDR       = {1'b1, 12'h004};

    localparam [BUS_ADDR_BITS-1:0] READ_READY_REG_ADDR = {1'b1, 12'h000};
    localparam [BUS_ADDR_BITS-1:0] BUSY_REG_ADDR       = {1'b1, 12'h001};
    localparam [BUS_ADDR_BITS-1:0] LOAD_READY_REG_ADDR = {1'b1, 12'h004};
    localparam [BUS_ADDR_BITS-1:0] DONE_REG_ADDR       = {1'b1, 12'h005};
    localparam [BUS_ADDR_BITS-1:0] LOAD_BANK_REG_ADDR  = {1'b1, 12'h006};
    localparam [BUS_ADDR_BITS-1:0] SESSION_REG_ADDR    = {1'b1, 12'h007};
    localparam [BUS_ADDR_BITS-1:0] MODE_REG_ADDR       = {1'b1, 12'h008};
    localparam [BUS_ADDR_BITS-1:0] OUTPUT_ROW_REG_ADDR = {1'b1, 12'h009};
    localparam [BUS_ADDR_BITS-1:0] STATE_REG_ADDR      = {1'b1, 12'h00A};

    reg CLK;
    reg RST;

    reg                      w_addr_valid_i;
    reg [31:0]               w_data_i;
    reg [BUS_ADDR_BITS-1:0]  w_addr_i;

    reg                      r_addr_valid_i;
    reg [BUS_ADDR_BITS-1:0]  r_addr_i;
    wire [31:0]              r_data_o;

    integer info_fd;
    integer input_fd;
    integer golden_fd;
    integer rtl_output_fd;

    integer image_width;
    integer image_height;
    integer scan_width_status;
    integer scan_height_status;
    integer scan_input_status;
    integer scan_golden_status;

    integer x;
    integer row;
    integer rows_loaded;
    integer rows_read;
    integer pass_count;
    integer fail_count;
    integer timeout_count;

    reg [7:0]  input_pixel;
    reg [7:0]  golden_pixel;
    reg [31:0] actual_data;
    reg [31:0] status_data;
    reg [31:0] bank_data;
    reg [31:0] row_index_data;
    reg [31:0] mode_data;

    Median_Filter_Core #(
        .MEM_ADDR_BITS (MEM_ADDR_BITS),
        .BUS_ADDR_BITS (BUS_ADDR_BITS),
        .DIM_BITS      (DIM_BITS)
    ) dut (
        .CLK            (CLK),
        .RST            (RST),
        .w_addr_valid_i (w_addr_valid_i),
        .w_data_i       (w_data_i),
        .w_addr_i       (w_addr_i),
        .r_addr_valid_i (r_addr_valid_i),
        .r_addr_i       (r_addr_i),
        .r_data_o       (r_data_o)
    );

    initial begin
        CLK = 1'b0;
        forever #(CLK_PERIOD/2) CLK = ~CLK;
    end


    function [7:0] hex_char_upper;
        input [3:0] nibble;
        begin
            if (nibble < 10)
                hex_char_upper = "0" + nibble;
            else
                hex_char_upper = "A" + (nibble - 10);
        end
    endfunction

    task write_hex_byte_upper;
        input [7:0] value;
        begin
            $fwrite(rtl_output_fd, "%c%c\n",
                    hex_char_upper(value[7:4]),
                    hex_char_upper(value[3:0]));
        end
    endtask

    task write_reg;
        input [BUS_ADDR_BITS-1:0] addr;
        input [31:0] data;
        begin
            @(negedge CLK);
            w_addr_valid_i = 1'b1;
            w_addr_i       = addr;
            w_data_i       = data;

            @(negedge CLK);
            w_addr_valid_i = 1'b0;
            w_addr_i       = {BUS_ADDR_BITS{1'b0}};
            w_data_i       = 32'b0;
        end
    endtask

    task read_reg;
        input  [BUS_ADDR_BITS-1:0] addr;
        output [31:0] data;
        begin
            // Drive the read request on the falling edge.
            // The Arbiter captures r_addr_valid_i/r_addr_i at the next
            // rising edge.  r_data_o is now a combinational decode of the
            // registered request/address (and of the synchronous Output BRAM
            // read data for memory-space accesses), so the response is valid
            // by the following falling edge: one clock after the request.
            @(negedge CLK);
            r_addr_valid_i = 1'b1;
            r_addr_i       = addr;

            @(negedge CLK);
            data = r_data_o;

            // End the request only after sampling the valid response.
            // Do not wait another clock here; that would sample after
            // r_addr_valid_r has been cleared and r_data_o has returned to 0.
            r_addr_valid_i = 1'b0;
            r_addr_i       = {BUS_ADDR_BITS{1'b0}};
        end
    endtask

    task reset_dut;
        begin
            RST = 1'b0;
            w_addr_valid_i = 1'b0;
            w_data_i       = 32'b0;
            w_addr_i       = {BUS_ADDR_BITS{1'b0}};
            r_addr_valid_i = 1'b0;
            r_addr_i       = {BUS_ADDR_BITS{1'b0}};

            repeat (5) @(posedge CLK);
            @(negedge CLK);
            RST = 1'b1;
            repeat (2) @(posedge CLK);
        end
    endtask

    task wait_load_ready;
        begin
            status_data   = 32'b0;
            timeout_count = 0;
            while ((status_data[0] !== 1'b1) &&
                   (timeout_count < MAX_TIMEOUT_POLLS)) begin
                read_reg(LOAD_READY_REG_ADDR, status_data);
                timeout_count = timeout_count + 1;
            end

            if (timeout_count >= MAX_TIMEOUT_POLLS) begin
                read_reg(STATE_REG_ADDR, status_data);
                $display("[ERROR] Timeout waiting LOAD. state=%0d", status_data[2:0]);
                $finish;
            end
        end
    endtask

    task wait_read_ready;
        begin
            status_data   = 32'b0;
            timeout_count = 0;
            while ((status_data[0] !== 1'b1) &&
                   (timeout_count < MAX_TIMEOUT_POLLS)) begin
                read_reg(READ_READY_REG_ADDR, status_data);
                timeout_count = timeout_count + 1;
            end

            if (timeout_count >= MAX_TIMEOUT_POLLS) begin
                read_reg(STATE_REG_ADDR, status_data);
                $display("[ERROR] Timeout waiting READ. state=%0d", status_data[2:0]);
                $finish;
            end
        end
    endtask

    task load_one_row;
        input integer row_number;
        begin
            wait_load_ready;
            read_reg(LOAD_BANK_REG_ADDR, bank_data);

            $display("[TB] LOAD original row %0d -> Input Bank%0d",
                     row_number, bank_data[1:0] + 1);

            for (x = 0; x < image_width; x = x + 1) begin
                scan_input_status = $fscanf(input_fd, "%h\n", input_pixel);
                if (scan_input_status != 1) begin
                    $display("[ERROR] Cannot read noisy pixel row=%0d x=%0d",
                             row_number, x);
                    $finish;
                end

                write_reg({1'b0, x[MEM_ADDR_BITS-1:0]},
                          {24'b0, input_pixel});
            end

            // Row-loaded handshake.
            write_reg(START_REG_ADDR, 32'h0000_0001);
            rows_loaded = rows_loaded + 1;
        end
    endtask

    task read_and_check_one_row;
        input integer row_number;
        begin
            wait_read_ready;

            read_reg(OUTPUT_ROW_REG_ADDR, row_index_data);
            read_reg(MODE_REG_ADDR, mode_data);

            if (row_index_data[DIM_BITS-1:0] !== row_number) begin
                $display("[ERROR] Controller row index mismatch. expected=%0d got=%0d",
                         row_number, row_index_data[DIM_BITS-1:0]);
                $finish;
            end

            if ((row_number == 0) ||
                (row_number == (image_height - 1)) ||
                (image_width < 3) ||
                (image_height < 3)) begin
                $display("[TB] READ output row %0d (COPY mode)", row_number);
            end
            else begin
                $display("[TB] READ output row %0d (MEDIAN mode)", row_number);
            end

            for (x = 0; x < image_width; x = x + 1) begin
                read_reg({1'b0, x[MEM_ADDR_BITS-1:0]}, actual_data);

                scan_golden_status = $fscanf(golden_fd, "%h\n", golden_pixel);
                if (scan_golden_status != 1) begin
                    $display("[ERROR] Cannot read golden pixel row=%0d x=%0d",
                             row_number, x);
                    $finish;
                end

                write_hex_byte_upper(actual_data[7:0]);

                if (actual_data[7:0] === golden_pixel) begin
                    pass_count = pass_count + 1;
                end
                else begin
                    fail_count = fail_count + 1;
                    if (fail_count <= MAX_REPORTED_FAILURES) begin
                        $display("[FAIL] row=%0d x=%0d RTL=%02h C=%02h",
                                 row_number, x,
                                 actual_data[7:0], golden_pixel);
                    end
                end
            end

            // Output row has been consumed; Output Memory may be reused.
            write_reg(STOP_REG_ADDR, 32'h0000_0001);
            rows_read = rows_read + 1;
        end
    endtask

    initial begin
        RST = 1'b1;
        w_addr_valid_i = 1'b0;
        w_data_i       = 32'b0;
        w_addr_i       = {BUS_ADDR_BITS{1'b0}};
        r_addr_valid_i = 1'b0;
        r_addr_i       = {BUS_ADDR_BITS{1'b0}};

        rows_loaded = 0;
        rows_read   = 0;
        pass_count  = 0;
        fail_count  = 0;
        timeout_count = 0;

        info_fd = $fopen(IMAGE_INFO_FILE, "r");
        if (info_fd == 0) begin
            $display("[ERROR] Cannot open %s", IMAGE_INFO_FILE);
            $finish;
        end

        scan_width_status  = $fscanf(info_fd, "WIDTH=%d\n", image_width);
        scan_height_status = $fscanf(info_fd, "HEIGHT=%d\n", image_height);
        $fclose(info_fd);

        if ((scan_width_status != 1) || (scan_height_status != 1)) begin
            $display("[ERROR] Invalid image_info.txt format.");
            $finish;
        end

        if ((image_width <= 0) || (image_width > BANK_DEPTH)) begin
            $display("[ERROR] Unsupported WIDTH=%0d. Input/Output row BRAM depth=%0d.",
                     image_width, BANK_DEPTH);
            $finish;
        end

        if (image_height <= 0) begin
            $display("[ERROR] Invalid HEIGHT=%0d", image_height);
            $finish;
        end

        input_fd = $fopen(INPUT_HEX_FILE, "r");
        if (input_fd == 0) begin
            $display("[ERROR] Cannot open %s", INPUT_HEX_FILE);
            $finish;
        end

        golden_fd = $fopen(GOLDEN_HEX_FILE, "r");
        if (golden_fd == 0) begin
            $display("[ERROR] Cannot open %s", GOLDEN_HEX_FILE);
            $finish;
        end

        rtl_output_fd = $fopen(RTL_OUTPUT_FILE, "w");
        if (rtl_output_fd == 0) begin
            $display("[ERROR] Cannot open %s", RTL_OUTPUT_FILE);
            $finish;
        end

        $display("");
        $display("============================================================");
        $display(" MEDIAN FILTER - OUT-OF-PLACE 3-BANK TILING VERIFICATION");
        $display("============================================================");
        $display("Resolution    : %0d x %0d", image_width, image_height);
        $display("Input banks   : 3 x %0d x 8 bits", BANK_DEPTH);
        $display("Output memory : 1 x %0d x 8 bits (row buffer)", BANK_DEPTH);
        $display("Golden        : denoised_pixels.hex from median_filter.c");
        $display("============================================================");

        reset_dut;

        write_reg(WIDTH_REG_ADDR,  image_width);
        write_reg(HEIGHT_REG_ADDR, image_height);
        write_reg(LOAD_REG_ADDR,   32'h0000_0001);

        if ((image_width < 3) || (image_height < 3)) begin
            // Same early-return behavior as C: output=input for the whole frame.
            for (row = 0; row < image_height; row = row + 1) begin
                load_one_row(row);
                read_and_check_one_row(row);
            end
        end
        else begin
            // Initial three original input rows.
            load_one_row(0);
            load_one_row(1);
            load_one_row(2);

            // Separate output buffer first receives the unchanged top border.
            read_and_check_one_row(0);

            // Controller automatically computes row1 from original rows 0/1/2.
            read_and_check_one_row(1);

            // Every next original input row reuses only the obsolete top bank.
            // Input rows are never overwritten by median results.
            for (row = 3; row < image_height; row = row + 1) begin
                load_one_row(row);
                read_and_check_one_row(row - 1);
            end

            // Controller automatically copies the unchanged bottom border row.
            read_and_check_one_row(image_height - 1);
        end

        repeat (4) @(posedge CLK);
        read_reg(DONE_REG_ADDR, status_data);

        $fclose(input_fd);
        $fclose(golden_fd);
        $fclose(rtl_output_fd);

        $display("");
        $display("============================================================");
        $display("                    TEST SUMMARY");
        $display("============================================================");
        $display("Rows loaded : %0d", rows_loaded);
        $display("Rows read   : %0d", rows_read);
        $display("PASS pixels : %0d", pass_count);
        $display("FAIL pixels : %0d", fail_count);
        $display("DONE        : %0d", status_data[0]);
        $display("RTL output  : %s", RTL_OUTPUT_FILE);
        $display("============================================================");

        if ((fail_count == 0) &&
            (rows_loaded == image_height) &&
            (rows_read == image_height) &&
            (status_data[0] == 1'b1)) begin
            $display("RESULT      : ALL TESTS PASSED - RTL MATCHES C GOLDEN");
        end
        else begin
            $display("RESULT      : TEST FAILED");
        end

        $display("============================================================");

        #100;
        $finish;
    end

endmodule
