# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/SoC/SoC.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC || ORIG_REF_NAME==SoC} -quiet] -quiet

# IP: bd/SoC/ip/SoC_zynq_ultra_ps_e_0_0/SoC_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==SoC_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_xbar_0/SoC_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_xbar_0 || ORIG_REF_NAME==SoC_xbar_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_ps8_0_axi_periph_0/SoC_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_ps8_0_axi_periph_0 || ORIG_REF_NAME==SoC_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_rst_ps8_0_99M_0/SoC_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_rst_ps8_0_99M_0 || ORIG_REF_NAME==SoC_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_H_Acceleration_IP_0_1/SoC_H_Acceleration_IP_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_H_Acceleration_IP_0_1 || ORIG_REF_NAME==SoC_H_Acceleration_IP_0_1} -quiet] -quiet

# IP: bd/SoC/ip/SoC_auto_ds_0/SoC_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_auto_ds_0 || ORIG_REF_NAME==SoC_auto_ds_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_auto_pc_0/SoC_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_auto_pc_0 || ORIG_REF_NAME==SoC_auto_pc_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_auto_ds_1/SoC_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_auto_ds_1 || ORIG_REF_NAME==SoC_auto_ds_1} -quiet] -quiet

# IP: bd/SoC/ip/SoC_auto_pc_1/SoC_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_auto_pc_1 || ORIG_REF_NAME==SoC_auto_pc_1} -quiet] -quiet

# XDC: c:/SOC_basic/buoi2/SoC/SoC.gen/sources_1/bd/SoC/SoC_ooc.xdc
