# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/SOC_basic/buoi2/SoC/SoC.srcs/sources_1/bd/SoC/ip/SoC_xbar_0/SoC_xbar_0.xci
# IP: The module: 'SoC_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SOC_basic/buoi2/SoC/SoC.gen/sources_1/bd/SoC/ip/SoC_xbar_0/SoC_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SoC_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/SOC_basic/buoi2/SoC/SoC.srcs/sources_1/bd/SoC/ip/SoC_xbar_0/SoC_xbar_0.xci
# IP: The module: 'SoC_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SOC_basic/buoi2/SoC/SoC.gen/sources_1/bd/SoC/ip/SoC_xbar_0/SoC_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SoC_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
